### ISSUE TITLE
Setup user accounts

### ISSUE THREAD

**Issue by hornunjb** [hornunjb/AnxietyKnot#24]

**Comment by uc-kokengna** [comment]
Currently in progress of creating this. Have the setup and login pages directed to HTML pages, wanting to have dropdown feature implemented instead if can. Now working on the backend setup along with establishing encryption and authentication methods.

**Comment by uc-kokengna** [comment]
FROM LAST SEMESTER: Created component/UI for login and Signup
![image](https://user-images.githubusercontent.com/70075871/149630226-d256d060-a65e-49e1-b16c-b3e30b457847.png)
![image](https://user-images.githubusercontent.com/70075871/149630231-8d609670-afba-4c10-aa24-e1c394e55c63.png)

**Comment by uc-kokengna** [comment]
Currently in proccess of authenticating the submission of user login/account creation via encrypted json web tokens.
![image](https://user-images.githubusercontent.com/70075871/149630362-286f7593-2dae-4298-85fb-550afdc54723.png)
Example on Mongo DB: userEmail, and encryptedPassword

**Comment by uc-kokengna** [comment]
Problems discovered with the backend mongoose schema not posting posts text to MongoDB. Figured out it has to do with the "required" parameter in the post.js models backend folder. This required parameter acts as a middleware validator which is possible conflicting with other "middleware" folder. Will need to do a rollback to see if this issue can be bypassed by removing any nonessential features that may cause current and future post uploading conflictions.

**Comment by uc-kokengna** [comment]
Signup: Accounts are created using an email and password. The user account is stored within the database with an assigned objectId and password is encrypted. Attempted signup of an email already in use will throw an error and throw the user back into the signup page.

![image](https://user-images.githubusercontent.com/70075871/153075062-c73e53ce-75af-4969-b7d8-b8eaffb022d4.png)

**Comment by uc-kokengna** [comment]
Login: Users that created an account will be given a Json Web token with a timer (1hour) until the user needs to obtain another json web token.
![image](https://user-images.githubusercontent.com/70075871/153075750-da99097e-6210-4406-bdae-3bcceedc2cbd.png)

This token is stored within local storage, i.e. browser. And it is tied to the userId of the account logged in.
![image](https://user-images.githubusercontent.com/70075871/153075905-b536070f-c330-4982-b4cc-48e8a4bdf8c2.png)

Upon loggout, the json web token for the user is deleted and will be reobtained upon another login. This same proccess also occurs if a user stays logged in for over 1 hour. In which case, the expiration timer for the JWT will be automatically deleted, the user will be automatically logged out and will need to reobtain another JWT via login.
![image](https://user-images.githubusercontent.com/70075871/153076321-40b053f7-c90f-4735-9532-87e5263ea3a7.png)

**Comment by uc-kokengna** [comment]
JWT Syntax: Used to verify authentication and authorization of users
<header, payload, signature>
header: token type and signing algorithm
payload: contains info of actual user (user email, user id...)
signature: a signature created by sever end to verify it was created by said server and ensure it was not altered.

![image](https://user-images.githubusercontent.com/70075871/153077406-ccb2de26-dcca-4be6-bf8e-a5c34662643d.png)
