### ISSUE TITLE
Only show journal entries to a user if they wrote them

### ISSUE THREAD

**Issue by hornunjb** [hornunjb/AnxietyKnot#58]

**Comment by uc-kokengna** [comment]
To show all posts created by all user accounts:
Journal-book.component.html

<mat-expansion-panel-header *ngIf="userIsAuthenticated " >  
        {{ post.title }}
![image](https://user-images.githubusercontent.com/70075871/153074154-a16d3fd5-e555-4805-ac8f-888c75dbfd41.png)

To show only posts created by the actual user:
Journal-book.component.html

<mat-expansion-panel-header *ngIf="userIsAuthenticated && userId === post.creator" >  
        {{ post.title }}
![image](https://user-images.githubusercontent.com/70075871/153074403-76642b22-942f-4829-9869-13073b12fc62.png)

**Comment by uc-kokengna** [comment]
successfullly able to have users display only posts they created for both unprompted and prompted
![image](https://user-images.githubusercontent.com/70075871/154816586-b7129aef-d48d-41fb-96b4-bf8e8b1a331b.png)
![image](https://user-images.githubusercontent.com/70075871/154816598-4522ef5d-05ee-4153-ade7-a6ce5a638c2c.png)
![image](https://user-images.githubusercontent.com/70075871/154816631-70717e61-7a50-4954-a704-ade91ab48980.png)

**Comment by uc-kokengna** [comment]
Fixed issues that lead to duplication of deleted posts re-appearing in UI. Had to make a 'display.service.ts' to compensate for the creation of the 'journalDisplay.model.ts' model to contain all 'entry.service.ts' and 'posts.service.ts' code to have journalDisplay.component.ts distinquish some issues (this solved duplicate issue, still not 100% how but majority wise I believe I understand)

Implemented the edit selection (when choosing the post or entries) to successfully update and save; an issue with obtaining objectId of prompted and unprompted entries (posts and entries).
![image](https://user-images.githubusercontent.com/70075871/157340928-0d2dd9ca-dc76-44d0-a047-500fc1029ef7.png)
![image](https://user-images.githubusercontent.com/70075871/157340965-20d10422-3960-4e37-b4af-d40065ef6634.png)
