### ISSUE TITLE
Fix duplication issue on journal-display component when creating/editing journal entries

### ISSUE THREAD

**Issue by hornunjb** [hornunjb/AnxietyKnot#82]

**Comment by uc-kokengna** [comment]
Did ALOT of QAT and discovered a few problem areas leading to the duplication bug. And Fixes.
![image](https://user-images.githubusercontent.com/70075871/161335486-682127b9-e885-41a4-bb73-8269f97ca1ce.png)

**Comment by hornunjb** [comment]
https://github.com/hornunjb/AnxietyKnot/commit/fb785e45bc385deb07b5581f8164198b405d675e
